//! Native loopback callback server: a `tiny_http` listener that catches
//! the `127.0.0.1:NATIVE_CALLBACK_PORT/callback?code=&state=` redirect
//! from the authorization server and ships the pair through a channel
//! back into the Bevy frame loop.
//!
//! Cross-site request hardening: only requests whose URL path starts
//! with `/callback` *and* whose `state` query parameter matches the
//! cryptographically random value generated by
//! `proto_blue_oauth::OAuthClient::authorize()` terminate the listener.
//! Garbage requests are answered with a 404 and the loop continues
//! listening — a malicious browser tab can no longer brick the in-flight
//! login attempt by issuing a forged `fetch()` to our loopback port.

use bevy::prelude::*;

/// Channel carrying the `code` / `state` pair from the loopback callback
/// server back to the Bevy polling system.
#[derive(Resource)]
pub struct NativeCallbackReceiver(
    pub std::sync::Mutex<std::sync::mpsc::Receiver<(String, String)>>,
);

/// Start a one-shot `tiny_http` server on the configured port, parse the
/// first `/callback?code=&state=` request whose `state` query parameter
/// matches `expected_state`, send the pair through a channel, and shut
/// down. Runs on a detached thread so the Bevy frame loop is not blocked.
///
/// Returns the receive side of the channel — the caller is expected to
/// insert it as [`NativeCallbackReceiver`] and poll it in a Bevy system.
pub fn start_native_callback_server(
    expected_state: String,
) -> Result<std::sync::mpsc::Receiver<(String, String)>, String> {
    use std::thread;

    use super::discovery::NATIVE_CALLBACK_PORT;

    if expected_state.is_empty() {
        // Defence in depth: an empty expected state would let any caller
        // pass `state=` (or omit it entirely) and shut the listener down.
        // proto-blue-oauth always populates `app_state`, so this branch
        // signals a programming error rather than user-driven failure.
        return Err("start_native_callback_server: expected_state is empty".into());
    }

    let (tx, rx) = std::sync::mpsc::channel();
    let addr = format!("127.0.0.1:{NATIVE_CALLBACK_PORT}");
    let server = tiny_http::Server::http(&addr).map_err(|e| format!("bind {addr}: {e}"))?;

    thread::spawn(move || {
        for req in server.incoming_requests() {
            let url = req.url().to_string();
            let path_ok = url
                .split('?')
                .next()
                .map(|p| p == "/callback" || p.starts_with("/callback/"))
                .unwrap_or(false);
            let (code, state) = parse_callback_query(&url);

            let state_matches = state.as_deref().is_some_and(|s| s == expected_state);
            let is_authorized_callback = path_ok && code.is_some() && state_matches;

            let response = if is_authorized_callback {
                tiny_http::Response::from_string(
                    "<!doctype html><html><body><h2>Login successful.</h2>\
                     <p>You can close this tab and return to Symbios Overlands.</p></body></html>",
                )
                .with_header(
                    "Content-Type: text/html; charset=utf-8"
                        .parse::<tiny_http::Header>()
                        .unwrap(),
                )
            } else {
                // Reject everything else with a 404. Crucially we do NOT
                // break the listener loop here — a forged request from
                // another browser tab must not be able to take the
                // server down before the real authorization-server
                // redirect arrives.
                tiny_http::Response::from_string("Not found")
                    .with_status_code(404)
                    .with_header(
                        "Content-Type: text/plain; charset=utf-8"
                            .parse::<tiny_http::Header>()
                            .unwrap(),
                    )
            };
            let _ = req.respond(response);

            if is_authorized_callback && let (Some(code), Some(state)) = (code, state) {
                let _ = tx.send((code, state));
                break;
            }
        }
    });

    Ok(rx)
}

/// Parse `code` and `state` out of a URL like `/callback?code=abc&state=xyz`.
///
/// Exposed so the integration-test suite in `tests/` can exercise the
/// native-loopback callback parser end-to-end; no production caller outside
/// this module invokes it directly.
pub fn parse_callback_query(url: &str) -> (Option<String>, Option<String>) {
    let Some(q_start) = url.find('?') else {
        return (None, None);
    };
    let query = &url[q_start + 1..];
    let mut code = None;
    let mut state = None;
    for pair in query.split('&') {
        let mut it = pair.splitn(2, '=');
        let k = it.next().unwrap_or("");
        let v = it.next().unwrap_or("");
        let decoded = percent_decode(v);
        match k {
            "code" => code = Some(decoded),
            "state" => state = Some(decoded),
            _ => {}
        }
    }
    (code, state)
}

fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                let h = hex(bytes[i + 1]);
                let l = hex(bytes[i + 2]);
                match (h, l) {
                    (Some(h), Some(l)) => {
                        out.push((h << 4) | l);
                        i += 3;
                    }
                    _ => {
                        out.push(bytes[i]);
                        i += 1;
                    }
                }
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hex(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}
