//! Native loopback callback server: a `tiny_http` listener that catches
//! the `127.0.0.1:NATIVE_CALLBACK_PORT/callback?code=&state=` redirect
//! from the authorization server — or its `?error=&state=` error twin
//! (user denied, expired request, …) — and ships the outcome through a
//! channel back into the Bevy frame loop.
//!
//! Cross-site request hardening: only requests whose URL path starts
//! with `/callback` *and* whose `state` query parameter matches the
//! cryptographically random value generated by
//! `proto_blue_oauth::OAuthClient::authorize()` terminate the listener.
//! Garbage requests are answered with a 404 and the loop continues
//! listening — a malicious browser tab can no longer brick the in-flight
//! login attempt by issuing a forged `fetch()` to our loopback port.

use bevy::prelude::*;

use super::util::{CallbackParams, parse_query_params};

/// Terminal outcome shipped from the loopback listener back into the
/// Bevy frame loop. `state` was already validated against the expected
/// value by the listener, so it is not carried.
pub enum NativeCallbackOutcome {
    /// Authorization code from a successful consent.
    Code(String),
    /// The AS's error redirect (user denied, expired request, …),
    /// pre-formatted for the login UI by
    /// [`CallbackParams::error_message`].
    Error(String),
}

/// Channel carrying the callback outcome from the loopback callback
/// server back to the Bevy polling system.
#[derive(Resource)]
pub struct NativeCallbackReceiver(
    pub std::sync::Mutex<std::sync::mpsc::Receiver<NativeCallbackOutcome>>,
);

/// Owning handle to a running loopback listener. The accept loop blocks
/// in `incoming_requests()` until an authorized callback arrives, so an
/// abandoned login attempt (browser tab closed before the redirect)
/// would otherwise pin the port forever and make every retry fail with
/// `AddrInUse` until an app restart. [`shutdown`](Self::shutdown) — also
/// run on drop — unblocks the loop and joins the thread, releasing the
/// port for the next bind.
pub struct NativeCallbackServerHandle {
    server: std::sync::Arc<tiny_http::Server>,
    thread: Option<std::thread::JoinHandle<()>>,
}

impl NativeCallbackServerHandle {
    /// Unblock the accept loop and join the listener thread. Dropping
    /// the last `Arc<Server>` closes the socket, so a subsequent
    /// [`start_native_callback_server`] can rebind the port immediately.
    /// Idempotent; the join is prompt because `tiny_http::Server::
    /// unblock` queues a sentinel even when the thread is mid-response.
    pub fn shutdown(&mut self) {
        self.server.unblock();
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

impl Drop for NativeCallbackServerHandle {
    fn drop(&mut self) {
        self.shutdown();
    }
}

/// Bevy resource owning the current listener (if any). `Option` so the
/// login-begin system can `take()` and shut down a leftover listener
/// before binding a fresh one.
#[derive(Resource)]
pub struct NativeCallbackServerRes(pub Option<NativeCallbackServerHandle>);

/// Start a one-shot `tiny_http` server on the configured port, parse the
/// first `/callback?code=&state=` request whose `state` query parameter
/// matches `expected_state`, send the pair through a channel, and shut
/// down. Runs on a detached thread so the Bevy frame loop is not blocked.
///
/// Returns the receive side of the channel plus the server handle — the
/// caller is expected to insert them as [`NativeCallbackReceiver`] /
/// [`NativeCallbackServerRes`] and poll the channel in a Bevy system.
pub fn start_native_callback_server(
    expected_state: String,
) -> Result<
    (
        std::sync::mpsc::Receiver<NativeCallbackOutcome>,
        NativeCallbackServerHandle,
    ),
    String,
> {
    use std::thread;

    use super::discovery::NATIVE_CALLBACK_PORT;

    if expected_state.is_empty() {
        // Defence in depth: an empty expected state would let any caller
        // pass `state=` (or omit it entirely) and shut the listener down.
        // proto-blue-oauth always populates `app_state`, so this branch
        // signals a programming error rather than user-driven failure.
        return Err("start_native_callback_server: expected_state is empty".into());
    }

    let (tx, rx) = std::sync::mpsc::channel();
    let addr = format!("127.0.0.1:{NATIVE_CALLBACK_PORT}");
    let server = std::sync::Arc::new(
        tiny_http::Server::http(&addr).map_err(|e| format!("bind {addr}: {e}"))?,
    );

    let server_for_thread = std::sync::Arc::clone(&server);
    let thread = thread::spawn(move || {
        for req in server_for_thread.incoming_requests() {
            let url = req.url().to_string();
            let path_ok = url
                .split('?')
                .next()
                .map(|p| p == "/callback" || p.starts_with("/callback/"))
                .unwrap_or(false);
            let params = parse_callback_query(&url);

            let state_matches = params.state.as_deref().is_some_and(|s| s == expected_state);
            let is_authorized_code = path_ok && state_matches && params.code.is_some();
            // The AS's error redirect (RFC 6749 §4.1.2.1) — the user
            // clicked *Deny*, the request expired, etc. It carries the
            // same `state` echo as a success, so the match above still
            // protects against a forged cancel from another tab.
            let is_authorized_error =
                path_ok && state_matches && !is_authorized_code && params.error.is_some();

            let response = if is_authorized_code {
                html_response(
                    "<!doctype html><html><body><h2>Login successful.</h2>\
                     <p>You can close this tab and return to Symbios Overlands.</p></body></html>",
                )
            } else if is_authorized_error {
                html_response(
                    "<!doctype html><html><body><h2>Login was cancelled.</h2>\
                     <p>You can close this tab and return to Symbios Overlands \
                     to try again.</p></body></html>",
                )
            } else {
                // Reject everything else with a 404. Crucially we do NOT
                // break the listener loop here — a forged request from
                // another browser tab must not be able to take the
                // server down before the real authorization-server
                // redirect arrives.
                tiny_http::Response::from_string("Not found")
                    .with_status_code(404)
                    .with_header(
                        "Content-Type: text/plain; charset=utf-8"
                            .parse::<tiny_http::Header>()
                            .unwrap(),
                    )
            };
            let _ = req.respond(response);

            if is_authorized_code && let Some(code) = params.code {
                let _ = tx.send(NativeCallbackOutcome::Code(code));
                break;
            }
            if is_authorized_error {
                let msg = params
                    .error_message()
                    .unwrap_or_else(|| "Login failed at the authorization server.".to_string());
                let _ = tx.send(NativeCallbackOutcome::Error(msg));
                break;
            }
        }
    });

    Ok((
        rx,
        NativeCallbackServerHandle {
            server,
            thread: Some(thread),
        },
    ))
}

/// Shared HTML success/cancel response builder for the terminal
/// listener answers.
fn html_response(body: &str) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {
    tiny_http::Response::from_string(body).with_header(
        "Content-Type: text/html; charset=utf-8"
            .parse::<tiny_http::Header>()
            .unwrap(),
    )
}

/// Parse the recognised callback parameters out of a URL like
/// `/callback?code=abc&state=xyz` (or its `?error=access_denied&…`
/// error-redirect twin).
///
/// Exposed so the integration-test suite in `tests/` can exercise the
/// native-loopback callback parser end-to-end; no production caller outside
/// this module invokes it directly.
pub fn parse_callback_query(url: &str) -> CallbackParams {
    let Some(q_start) = url.find('?') else {
        return CallbackParams::default();
    };
    parse_query_params(&url[q_start + 1..])
}
