//! Native loopback callback server: a `tiny_http` listener that catches
//! the `127.0.0.1:NATIVE_CALLBACK_PORT/callback?code=&state=` redirect
//! from the authorization server — or its `?error=&state=` error twin
//! (user denied, expired request, …) — and ships the outcome through a
//! channel back into the Bevy frame loop.
//!
//! Cross-site request hardening: only requests whose URL path starts
//! with `/callback` *and* whose `state` query parameter matches the
//! cryptographically random value generated by
//! `proto_blue_oauth::OAuthClient::authorize()` terminate the listener.
//! Garbage requests are answered with a 404 and the loop continues
//! listening — a malicious browser tab can no longer brick the in-flight
//! login attempt by issuing a forged `fetch()` to our loopback port.

use bevy::prelude::*;

use super::util::{CallbackParams, parse_query_params};

/// Terminal outcome shipped from the loopback listener back into the
/// Bevy frame loop. `state` was already validated against the expected
/// value by the listener, so it is not carried.
pub enum NativeCallbackOutcome {
    /// Authorization code from a successful consent.
    Code(String),
    /// The AS's error redirect (user denied, expired request, …),
    /// pre-formatted for the login UI by
    /// [`CallbackParams::error_message`].
    Error(String),
}

/// Channel carrying the callback outcome from the loopback callback
/// server back to the Bevy polling system.
#[derive(Resource)]
pub struct NativeCallbackReceiver(
    pub std::sync::Mutex<std::sync::mpsc::Receiver<NativeCallbackOutcome>>,
);

/// Owning handle to a running loopback listener. The accept loop blocks
/// in `incoming_requests()` until an authorized callback arrives, so an
/// abandoned login attempt (browser tab closed before the redirect)
/// would otherwise pin the port forever and make every retry fail with
/// `AddrInUse` until an app restart. [`shutdown`](Self::shutdown) — also
/// run on drop — unblocks the loop and joins the thread, releasing the
/// port for the next bind.
pub struct NativeCallbackServerHandle {
    server: std::sync::Arc<tiny_http::Server>,
    thread: Option<std::thread::JoinHandle<()>>,
}

impl NativeCallbackServerHandle {
    /// Unblock the accept loop and join the listener thread. Dropping
    /// the last `Arc<Server>` closes the socket, so a subsequent
    /// [`start_native_callback_server`] can rebind the port immediately.
    /// Idempotent; the join is prompt because `tiny_http::Server::
    /// unblock` queues a sentinel even when the thread is mid-response.
    pub fn shutdown(&mut self) {
        self.server.unblock();
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

impl Drop for NativeCallbackServerHandle {
    fn drop(&mut self) {
        self.shutdown();
    }
}

/// Bevy resource owning the current listener (if any). `Option` so the
/// login-begin system can `take()` and shut down a leftover listener
/// before binding a fresh one.
#[derive(Resource)]
pub struct NativeCallbackServerRes(pub Option<NativeCallbackServerHandle>);

/// Start a one-shot `tiny_http` server on the configured port, parse the
/// first `/callback?code=&state=` request whose `state` query parameter
/// matches `expected_state`, send the pair through a channel, and shut
/// down. Runs on a detached thread so the Bevy frame loop is not blocked.
///
/// Returns the receive side of the channel plus the server handle — the
/// caller is expected to insert them as [`NativeCallbackReceiver`] /
/// [`NativeCallbackServerRes`] and poll the channel in a Bevy system.
pub fn start_native_callback_server(
    expected_state: String,
) -> Result<
    (
        std::sync::mpsc::Receiver<NativeCallbackOutcome>,
        NativeCallbackServerHandle,
    ),
    String,
> {
    use std::thread;

    use super::discovery::NATIVE_CALLBACK_PORT;

    if expected_state.is_empty() {
        // Defence in depth: an empty expected state would let any caller
        // pass `state=` (or omit it entirely) and shut the listener down.
        // proto-blue-oauth always populates `app_state`, so this branch
        // signals a programming error rather than user-driven failure.
        return Err("start_native_callback_server: expected_state is empty".into());
    }

    let (tx, rx) = std::sync::mpsc::channel();
    let addr = format!("127.0.0.1:{NATIVE_CALLBACK_PORT}");
    let server = std::sync::Arc::new(
        tiny_http::Server::http(&addr).map_err(|e| format!("bind {addr}: {e}"))?,
    );

    let server_for_thread = std::sync::Arc::clone(&server);
    let thread = thread::spawn(move || {
        for req in server_for_thread.incoming_requests() {
            let url = req.url().to_string();
            let path_ok = url
                .split('?')
                .next()
                .map(|p| p == "/callback" || p.starts_with("/callback/"))
                .unwrap_or(false);
            let params = parse_callback_query(&url);

            let state_matches = params.state.as_deref().is_some_and(|s| s == expected_state);
            let answer = classify_callback(
                path_ok,
                state_matches,
                params.code.is_some(),
                params.error.is_some(),
            );

            let response = match answer {
                CallbackAnswer::Code => html_response(&styled_page(
                    "Login successful.",
                    "You can close this tab and return to Symbios Overlands.",
                )),
                CallbackAnswer::Denied => html_response(&styled_page(
                    "Login was cancelled.",
                    "You can close this tab and return to Symbios Overlands to try again.",
                )),
                CallbackAnswer::Stale => html_response(&stale_page()).with_status_code(404),
                // Not our path at all — a scan, a favicon probe, a forged
                // request from another tab. Terse on purpose, and again we
                // do NOT break the listener loop: a stranger must not be
                // able to take the server down before the real
                // authorization-server redirect arrives.
                CallbackAnswer::NotFound => tiny_http::Response::from_string("Not found")
                    .with_status_code(404)
                    .with_header(
                        "Content-Type: text/plain; charset=utf-8"
                            .parse::<tiny_http::Header>()
                            .unwrap(),
                    ),
            };
            let _ = req.respond(response);

            if answer == CallbackAnswer::Code
                && let Some(code) = params.code
            {
                let _ = tx.send(NativeCallbackOutcome::Code(code));
                break;
            }
            if answer == CallbackAnswer::Denied {
                let msg = params
                    .error_message()
                    .unwrap_or_else(|| "Login failed at the authorization server.".to_string());
                let _ = tx.send(NativeCallbackOutcome::Error(msg));
                break;
            }
        }
    });

    Ok((
        rx,
        NativeCallbackServerHandle {
            server,
            thread: Some(thread),
        },
    ))
}

/// What the loopback listener does with one request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum CallbackAnswer {
    /// The authorization code this attempt was waiting for. Terminal.
    Code,
    /// This attempt's own error redirect (RFC 6749 §4.1.2.1) — the user
    /// clicked *Deny*, the request expired. Terminal.
    Denied,
    /// A well-formed `/callback` carrying somebody else's `state` (#1234
    /// f7). Refused, and the loop keeps listening.
    Stale,
    /// Not ours at all. Refused tersely, and the loop keeps listening.
    NotFound,
}

/// Classify one request. Pure, because the branch that matters is the one
/// nobody can see from inside the app: *Cancel* followed by *Enter* binds
/// a fresh listener with a new `expected_state`, so every consent tab
/// still open from an earlier attempt arrives here — and it is a real
/// callback from the real authorization server, not an attack.
///
/// The `state` check is still what protects the listener: an unmatched
/// state is never acted on, whatever the browser is told about it. All
/// this splits out is what the browser is told.
pub(crate) fn classify_callback(
    path_ok: bool,
    state_matches: bool,
    has_code: bool,
    has_error: bool,
) -> CallbackAnswer {
    if !path_ok {
        return CallbackAnswer::NotFound;
    }
    if !state_matches {
        return CallbackAnswer::Stale;
    }
    match (has_code, has_error) {
        (true, _) => CallbackAnswer::Code,
        (false, true) => CallbackAnswer::Denied,
        // Our path, our state, and neither half of a callback: nothing to
        // act on, and nothing to explain either.
        (false, false) => CallbackAnswer::NotFound,
    }
}

/// The page a superseded consent tab gets (#1234 f7).
///
/// It used to be an unbranded plain-text "Not found" while the app went on
/// saying "Complete the login in your browser…" — two surfaces each
/// looking broken, with the one remedy (use the newest tab, or Cancel and
/// retry) stated in neither. Still a 404; only the prose changed.
fn stale_page() -> String {
    styled_page(
        "This login link is out of date.",
        "Return to Symbios Overlands and use the newest login tab, or press Cancel there and try again.",
    )
}

/// Build the branded page shell for the terminal listener answers
/// (#860): dark surface + teal wordmark matching the app's dark theme
/// and the wasm splash, so the browser tab reads as the same product.
/// The heading/body copy is passed through verbatim — #847 chose that
/// wording deliberately.
fn styled_page(heading: &str, body: &str) -> String {
    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\">\
         <title>Symbios Overlands</title>\
         <meta name=\"theme-color\" content=\"#1b1b1b\"></head>\
         <body style=\"margin:0;height:100vh;display:flex;align-items:center;\
         justify-content:center;background:#1b1b1b;color:#dcdcdc;\
         font-family:system-ui,sans-serif;text-align:center\"><div>\
         <div style=\"color:#48c7d0;font-weight:700;letter-spacing:0.35em;\
         font-size:15px;margin-bottom:18px\">SYMBIOS&nbsp;OVERLANDS</div>\
         <h2 style=\"margin:0 0 8px 0;font-weight:600\">{heading}</h2>\
         <p style=\"margin:0;color:#9a9a9a\">{body}</p>\
         </div></body></html>"
    )
}

/// Shared HTML success/cancel response builder for the terminal
/// listener answers.
fn html_response(body: &str) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {
    tiny_http::Response::from_string(body).with_header(
        "Content-Type: text/html; charset=utf-8"
            .parse::<tiny_http::Header>()
            .unwrap(),
    )
}

/// Parse the recognised callback parameters out of a URL like
/// `/callback?code=abc&state=xyz` (or its `?error=access_denied&…`
/// error-redirect twin).
///
/// Exposed so the integration-test suite in `tests/` can exercise the
/// native-loopback callback parser end-to-end; no production caller outside
/// this module invokes it directly.
pub fn parse_callback_query(url: &str) -> CallbackParams {
    let Some(q_start) = url.find('?') else {
        return CallbackParams::default();
    };
    parse_query_params(&url[q_start + 1..])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// THE SEQUENCE (#1234 f7): the user presses Cancel and then Enter, so
    /// two consent tabs are open. They approve the OLDER one. Its `state`
    /// belongs to the attempt that was cancelled, so the listener refuses
    /// it — correctly — and used to answer an unbranded plain-text "Not
    /// found" while the app went on saying "Complete the login in your
    /// browser…". Two surfaces each looking broken, and the remedy stated
    /// in neither.
    #[test]
    fn a_superseded_consent_tab_is_told_what_to_do_instead() {
        assert_eq!(
            classify_callback(true, false, true, false),
            CallbackAnswer::Stale,
            "a real callback for an earlier attempt"
        );
        let page = stale_page();
        assert!(
            page.contains("SYMBIOS"),
            "the tab must read as this product"
        );
        assert!(page.contains("out of date"), "{page}");
        assert!(
            page.contains("newest login tab") && page.contains("Cancel"),
            "the page has to name the remedy: {page}"
        );
    }

    /// And the split changes only what the browser is TOLD. The state
    /// check is what protects the listener, and every outcome it produced
    /// before still lands on the same arm.
    #[test]
    fn only_this_attempts_own_callback_is_ever_acted_on() {
        assert_eq!(
            classify_callback(true, true, true, false),
            CallbackAnswer::Code
        );
        assert_eq!(
            classify_callback(true, true, false, true),
            CallbackAnswer::Denied
        );
        // A code echoing the wrong state is refused, not exchanged — the
        // forged-cancel-from-another-tab case the state match exists for.
        assert_eq!(
            classify_callback(true, false, false, true),
            CallbackAnswer::Stale
        );
        // Our path and our state, but neither half of a callback: nothing
        // to act on and nothing to explain.
        assert_eq!(
            classify_callback(true, true, false, false),
            CallbackAnswer::NotFound
        );
        // Anything off `/callback` never even reaches the question.
        for state_matches in [true, false] {
            assert_eq!(
                classify_callback(false, state_matches, true, false),
                CallbackAnswer::NotFound
            );
        }
    }
}
