"""Regenerate `src/berlin/coverage_table.rs` from Berlin's ALKIS boundaries.

The table says, for every 250 m cell of a fixed grid over Berlin, whether the
cell lies wholly inside the state and, if so, which borough its centre is in.
A geodata square may only be placed on cells that are inside, so every layer
the region fetches (terrain, land use, buildings, trees) has data under it.

Fetch the two inputs (GeoJSON, EPSG:25833, licence dl-de/zero-2.0):

    for t in alkis_land:landesgrenze alkis_bezirke:bezirksgrenzen; do
      s=${t%%:*}
      curl -sS -G -o "$OUT/$s.json" "https://gdi.berlin.de/services/wfs/$s" \
        --data-urlencode service=WFS --data-urlencode version=2.0.0 \
        --data-urlencode request=GetFeature --data-urlencode "typeNames=$t" \
        --data-urlencode outputFormat=application/json
    done

then run, from the repository root (the downloads are data, never code, so
keep them outside this directory and run Python isolated):

    python3 -I crates/geodata/tools/coverage.py "$OUT/alkis_land.json" \
        "$OUT/alkis_bezirke.json" crates/geodata/src/berlin/coverage_table.rs

Needs numpy and Pillow. The state polygon is rasterised at 25 m and a cell
counts as inside only when all 100 of its samples are. That holds to the
sampling, not to the metre: Pillow fills a sample the outline touches, and a
border passing between samples goes unseen, so an inside cell may reach up to
about one sample (25 m) past the border. The decoders fill such a sliver from
its neighbours.
"""

import json
import sys

import numpy as np
from PIL import Image, ImageDraw

ORIGIN_E, ORIGIN_N = 368_000, 5_798_000
CELL = 250
COLS, ROWS = 200, 160
SUB = 25
K = CELL // SUB
W, H = COLS * K, ROWS * K
SYMBOLS = ".abcdefghijkl"


def raster(features, value_of):
    """Rasterise polygons at SUB metres, row 0 = north edge."""
    img = Image.new("I", (W, H), 0)
    draw = ImageDraw.Draw(img)
    top = ORIGIN_N + ROWS * CELL

    def px(q):
        return ((q[0] - ORIGIN_E) / SUB, (top - q[1]) / SUB)

    for feature in features:
        value = value_of(feature)
        geometry = feature["geometry"]
        polygons = geometry["coordinates"]
        if geometry["type"] == "Polygon":
            polygons = [polygons]
        for polygon in polygons:
            draw.polygon([px(q) for q in polygon[0]], fill=value)
            for hole in polygon[1:]:
                draw.polygon([px(q) for q in hole], fill=0)
    return np.asarray(img)


def main():
    land_path, boroughs_path, out_path = sys.argv[1:4]
    with open(land_path, encoding="utf-8") as f:
        land = json.load(f)["features"]
    with open(boroughs_path, encoding="utf-8") as f:
        boroughs = json.load(f)["features"]
    names = {int(b["properties"]["gem"]): b["properties"]["namgem"] for b in boroughs}
    assert sorted(names) == list(range(1, 13)), names

    state = raster(land, lambda f: 1) > 0
    borough = raster(boroughs, lambda f: int(f["properties"]["gem"]))
    inside = state.reshape(ROWS, K, COLS, K).all(axis=(1, 3))
    centre = borough[K // 2 :: K, K // 2 :: K][:ROWS, :COLS]
    assert not (inside & (centre == 0)).any(), "an inside cell has no borough at its centre"
    cells = np.where(inside, centre, 0)[::-1]  # row 0 = south

    lines = []
    for row in cells:
        runs, start = [], 0
        for x in range(1, COLS + 1):
            if x == COLS or row[x] != row[start]:
                runs.append(f"{SYMBOLS[row[start]]}{x - start}")
                start = x
        lines.append("".join(runs))

    with open(out_path, "w", encoding="utf-8") as out:
        out.write(
            "//! Which 250 m cells of Berlin a geodata square may cover, and their boroughs.\n"
            "//!\n"
            "//! GENERATED by `crates/geodata/tools/coverage.py` from the ALKIS state and\n"
            "//! borough boundaries (GDI Berlin WFS `alkis_land:landesgrenze` and\n"
            "//! `alkis_bezirke:bezirksgrenzen`, dl-de/zero-2.0, fetched 2026-10-08) - do\n"
            "//! not edit by hand; rerun the tool.\n"
            "//!\n"
            "//! One string per 250 m band of northing, south first. Each is a run-length\n"
            "//! list of `<symbol><count>` reading west to east: `.` for a cell not wholly\n"
            "//! inside Berlin, `a` to `l` for a cell inside it, by the borough (ALKIS\n"
            "//! `gem` code 1 to 12) its centre lies in. Wholly inside to the tool's 25 m\n"
            "//! sampling: a cell may reach about one sample past the border.\n\n"
            f"/// Easting of the grid's west edge, metres (EPSG:25833).\n"
            f"pub(super) const ORIGIN_E: i32 = {ORIGIN_E:_};\n"
            f"/// Northing of the grid's south edge, metres (EPSG:25833).\n"
            f"pub(super) const ORIGIN_N: i32 = {ORIGIN_N:_};\n"
            f"/// Side of one cell, metres.\n"
            f"pub(super) const CELL_M: i32 = {CELL};\n"
            f"/// Cells per row.\n"
            f"pub(super) const COLS: usize = {COLS};\n"
            f"/// The rows, south first.\n"
            f"pub(super) const ROWS: [&str; {ROWS}] = [\n"
        )
        for line in lines:
            out.write(f'    "{line}",\n')
        out.write("];\n")
    print(f"inside cells {int(inside.sum())}, area {inside.sum() * CELL * CELL / 1e6:.1f} km2, longest row {max(map(len, lines))} chars")


if __name__ == "__main__":
    main()
